### ISSUE TITLE
Implement a smarter approach to Dependabot

### ISSUE THREAD

**Issue by jeffkala** [networktocode/netutils#212]
### Environment
* netutils version:  future

### Proposed Functionality
Limit the scope of dependabot to only "production" or "direct" dependencies to avoid the noise.

### Use Case
Majority of the dependabot PRs we have are just closed since they're only affecting the development environment or dependencies of dependencies. 

Example:
```yaml
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
        dependency-type: "direct"
```
